In [199]:
import pandas as pd

In [200]:
melbourne_file_path = "melb_data.csv"

In [201]:
melbourne_data = pd.read_csv(melbourne_file_path)

In [202]:
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [203]:
melbourne_data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [204]:
melbourne_data[::-1]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0

In [205]:
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [206]:
melbourne_data = melbourne_data.dropna(axis=0)

In [207]:
melbourne_data # Without NaN homes

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.00,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.00,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.00,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.00,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
7,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.00,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12205,Whittlesea,30 Sherwin St,3,h,601000.0,S,Ray,29/07/2017,35.5,3757.0,...,2.0,1.0,972.0,149.00,1996.0,Whittlesea,-37.51232,145.13282,Northern Victoria,2170.0
12206,Williamstown,75 Cecil St,3,h,1050000.0,VB,Williams,29/07/2017,6.8,3016.0,...,1.0,0.0,179.0,115.00,1890.0,Hobsons Bay,-37.86558,144.90474,Western Metropolitan,6380.0
12207,Williamstown,2/29 Dover Rd,1,u,385000.0,SP,Williams,29/07/2017,6.8,3016.0,...,1.0,1.0,0.0,35.64,1967.0,Hobsons Bay,-37.85588,144.89936,Western Metropolitan,6380.0
12209,Windsor,201/152 Peel St,2,u,560000.0,PI,hockingstuart,29/07/2017,4.6,3181.0,...,1.0,1.0,0.0,61.60,2012.0,Stonnington,-37.85581,144.99025,Southern Metropolitan,4380.0
12212,Yarraville,54 Pentland Pde,6,h,2450000.0,VB,Village,29/07/2017,6.3,3013.0,...,3.0,2.0,1087.0,388.50,1920.0,Maribyrnong,-37.81038,144.89389,Western Metropolitan,6543.0

In [208]:
y = melbourne_data.Price

In [209]:
y

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
           ...
12205     601000.0
12206    1050000.0
12207     385000.0
12209     560000.0
12212    2450000.0
Name: Price, Length: 6196, dtype: float64

In [210]:
melbourne_data["Price"][0:5]

1    1035000.0
2    1465000.0
4    1600000.0
6    1876000.0
7    1636000.0
Name: Price, dtype: float64

In [211]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [212]:
melbourne_features

['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [213]:
X = melbourne_data[melbourne_features]

In [214]:
X

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
1          2       1.0     156.0  -37.80790   144.99340
2          3       2.0     134.0  -37.80930   144.99440
4          4       1.0     120.0  -37.80720   144.99410
6          3       2.0     245.0  -37.80240   144.99930
7          2       1.0     256.0  -37.80600   144.99540
...      ...       ...       ...        ...         ...
12205      3       2.0     972.0  -37.51232   145.13282
12206      3       1.0     179.0  -37.86558   144.90474
12207      1       1.0       0.0  -37.85588   144.89936
12209      2       1.0       0.0  -37.85581   144.99025
12212      6       3.0    1087.0  -37.81038   144.89389

[6196 rows x 5 columns]

In [215]:
melbourne_data[['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']]

       Rooms  Bathroom  Landsize  Lattitude  Longtitude
1          2       1.0     156.0  -37.80790   144.99340
2          3       2.0     134.0  -37.80930   144.99440
4          4       1.0     120.0  -37.80720   144.99410
6          3       2.0     245.0  -37.80240   144.99930
7          2       1.0     256.0  -37.80600   144.99540
...      ...       ...       ...        ...         ...
12205      3       2.0     972.0  -37.51232   145.13282
12206      3       1.0     179.0  -37.86558   144.90474
12207      1       1.0       0.0  -37.85588   144.89936
12209      2       1.0       0.0  -37.85581   144.99025
12212      6       3.0    1087.0  -37.81038   144.89389

[6196 rows x 5 columns]

In [216]:
X.describe()

             Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  6196.000000  6196.000000   6196.000000  6196.000000  6196.000000
mean      2.931407     1.576340    471.006940   -37.807904   144.990201
std       0.971079     0.711362    897.449881     0.075850     0.099165
min       1.000000     1.000000      0.000000   -38.164920   144.542370
25%       2.000000     1.000000    152.000000   -37.855438   144.926198
50%       3.000000     1.000000    373.000000   -37.802250   144.995800
75%       4.000000     2.000000    628.000000   -37.758200   145.052700
max       8.000000     8.000000  37000.000000   -37.457090   145.526350

In [217]:
X.head()

   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954

Define: What type of model will it be? A decision tree? Some other type of model? Some other parameters of the model type are specified too.

Fit: Capture patterns from provided data. This is the heart of modeling.

Predict: Just what it sounds like

Evaluate: Determine how accurate the model's predictions are.

In [218]:
from sklearn.tree import DecisionTreeRegressor

In [219]:
melbourne_model = DecisionTreeRegressor(random_state=1)

In [220]:
melbourne_model.fit(X, y)

DecisionTreeRegressor(random_state=1)

In [221]:
DecisionTreeRegressor(random_state=1)

DecisionTreeRegressor(random_state=1)

In [222]:
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]

In [223]:
y

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
           ...
12205     601000.0
12206    1050000.0
12207     385000.0
12209     560000.0
12212    2450000.0
Name: Price, Length: 6196, dtype: float64

## MAE

In [224]:
filtered_melbourne_data = melbourne_data.dropna(axis=0)

In [225]:
y = filtered_melbourne_data.Price

In [226]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'BuildingArea', 
                        'YearBuilt', 'Lattitude', 'Longtitude']

X = filtered_melbourne_data[melbourne_features]

In [227]:
from sklearn.tree import DecisionTreeRegressor

In [228]:
melbourne_model = DecisionTreeRegressor()

In [229]:
melbourne_model.fit(X, y)

DecisionTreeRegressor()

In [230]:
from sklearn.metrics import mean_absolute_error

In [231]:
predicted_home_prices = melbourne_model.predict(X)
mean_absolute_error(y, predicted_home_prices)

434.71594577146544

In [232]:
from sklearn.model_selection import train_test_split

In [233]:
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 4)

In [234]:
train_X

,Rooms,Bathroom,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
25,2,1.0,147.0,85.0,1900.0,-37.80800,144.99400
9903,4,2.0,680.0,230.0,2011.0,-37.61236,144.90753
3736,3,1.0,584.0,81.0,1900.0,-37.78850,144.87710
11043,3,2.0,853.0,28.0,1972.0,-37.88984,145.18016
6405,3,2.0,363.0,215.0,1935.0,-37.84450,145.01820
...,...,...,...,...,...,...,...
11834,3,2.0,198.0,143.0,2004.0,-37.69503,144.77869
1320,3,2.0,470.0,152.0,1920.0,-37.77880,144.96880
4515,2,1.0,189.0,85.0,1995.0,-37.71510,144.91910
313,3,2.0,532.0,147.0,1950.0,-37.77370,144.90400
2094,2,1.0,130.0,80.0,1890.0,-37.79530,144.98820

In [235]:
train_y

25       1315000.0
9903      715000.0
3736      840000.0
11043    1311000.0
6405     3270000.0
           ...
11834     502000.0
1320     1691500.0
4515      476000.0
313      1435000.0
2094      855000.0
Name: Price, Length: 4647, dtype: float64

In [236]:
val_X

,Rooms,Bathroom,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
6185,3,2.0,536.0,211.0,1930.0,-37.83090,145.09460
7150,4,2.0,557.0,178.0,1955.0,-37.90600,145.07400
56,3,2.0,165.0,133.0,2009.0,-37.72700,144.88700
5219,2,1.0,153.0,107.0,2003.0,-37.70200,145.03240
8636,3,1.0,98.0,101.0,1997.0,-37.79100,144.93230
...,...,...,...,...,...,...,...
8681,3,1.0,1678.0,94.0,1940.0,-37.83840,145.01780
6639,2,1.0,220.0,105.0,1910.0,-37.81150,144.88750
11064,3,2.0,471.0,144.0,1965.0,-37.82996,145.24311
5249,2,1.0,383.0,103.0,1970.0,-37.71030,145.00370
7647,4,2.0,518.0,160.0,1980.0,-37.76060,144.94990

In [237]:
val_y

6185     1251000.0
7150     1400000.0
56        700000.0
5219      420000.0
8636      917500.0
           ...
8681      840000.0
6639     1000000.0
11064     912000.0
5249      610000.0
7647     1205000.0
Name: Price, Length: 1549, dtype: float64

In [238]:
melbourne_model = DecisionTreeRegressor()

In [239]:
melbourne_model.fit(train_X, train_y)

DecisionTreeRegressor()

In [240]:
val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

267809.1349257586

in-sample data was 500~

out of sample data was 250000~

In [241]:
val_predictions[0:10]

array([1857000., 1700000.,  720000.,  475000., 1000000., 1240000.,
        702500., 1925000., 1160000.,  915000.])

In [242]:
val_y[0:10]

6185     1251000.0
7150     1400000.0
56        700000.0
5219      420000.0
8636      917500.0
870      1200000.0
7591      735000.0
11004    3175000.0
832      1415000.0
63        773000.0
Name: Price, dtype: float64

Numbers looks similar

## Underfitting and Overfitting

In [243]:
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

getting mae

In [244]:
def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [245]:
y

1        1035000.0
2        1465000.0
4        1600000.0
6        1876000.0
7        1636000.0
           ...
12205     601000.0
12206    1050000.0
12207     385000.0
12209     560000.0
12212    2450000.0
Name: Price, Length: 6196, dtype: float64

In [246]:
X

,Rooms,Bathroom,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
1,2,1.0,156.0,79.00,1900.0,-37.80790,144.99340
2,3,2.0,134.0,150.00,1900.0,-37.80930,144.99440
4,4,1.0,120.0,142.00,2014.0,-37.80720,144.99410
6,3,2.0,245.0,210.00,1910.0,-37.80240,144.99930
7,2,1.0,256.0,107.00,1890.0,-37.80600,144.99540
...,...,...,...,...,...,...,...
12205,3,2.0,972.0,149.00,1996.0,-37.51232,145.13282
12206,3,1.0,179.0,115.00,1890.0,-37.86558,144.90474
12207,1,1.0,0.0,35.64,1967.0,-37.85588,144.89936
12209,2,1.0,0.0,61.60,2012.0,-37.85581,144.99025
12212,6,3.0,1087.0,388.50,1920.0,-37.81038,144.89389

In [247]:
from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

In [248]:
train_X

,Rooms,Bathroom,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude
10385,3,1.0,206.0,110.0,1980.0,-37.87107,145.04991
5805,2,1.0,0.0,73.0,2000.0,-37.85900,144.97670
8488,2,1.0,2701.0,79.0,2011.0,-37.81090,144.86840
6672,3,1.0,670.0,116.0,1940.0,-37.81340,144.87450
776,6,3.0,708.0,275.0,1988.0,-37.91810,145.04400
...,...,...,...,...,...,...,...
9510,3,1.0,118.0,177.0,1890.0,-37.81351,144.98804
6023,5,2.0,661.0,133.0,1960.0,-37.76510,144.82410
2960,4,2.0,453.0,213.0,2007.0,-37.70160,144.89740
4729,2,1.0,90.0,106.0,2007.0,-37.83570,144.93760
4996,3,1.0,495.0,100.0,1950.0,-37.75210,145.01140

In [249]:
nums = []

In [250]:
for max_leaf_nodes in [5, 50, 500, 5000]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))
    nums.append(my_mae)

Max leaf nodes: 5  		 Mean Absolute Error:  347380
Max leaf nodes: 50  		 Mean Absolute Error:  258171
Max leaf nodes: 500  		 Mean Absolute Error:  243495
Max leaf nodes: 5000  		 Mean Absolute Error:  255575

In [251]:
lowest_num = min(nums)

lowest_num

243495.96361790417

In [252]:
nums

[347380.33833344496,
 258171.21202406782,
 243495.96361790417,
 255575.12911555843]

In [253]:
index_of_lowest_num = nums.index(lowest_num)

index_of_lowest_num

2

index 2 was 500

## Conclusion

Here's the takeaway: Models can suffer from either:

### Overfitting: capturing spurious patterns that won't recur in the future, leading to less accurate predictions, or
### Underfitting: failing to capture relevant patterns, again leading to less accurate predictions.

In [254]:
final_model = DecisionTreeRegressor(max_leaf_nodes=500, random_state=0) #100

# fit the final model and uncomment the next two lines
final_model.fit(X, y)

DecisionTreeRegressor(max_leaf_nodes=500, random_state=0)

In [255]:
val_predictions = melbourne_model.predict(val_X)
print(mean_absolute_error(val_y, val_predictions))

76016.15752098127

In [262]:
val_predictions[123:140]

array([ 930000.,  505000., 1725000.,  800000., 1197000.,  390000.,
       1300000.,  800000.,  580000., 1935000., 3400000.,  430000.,
       1400000.,  570000.,  767000., 2450000.,  925000.])

In [261]:
val_y[123:140]

861       930000.0
10942     505000.0
1053     1725000.0
3612      800000.0
711      1110000.0
8844      390000.0
5897     1300000.0
10286     755000.0
5824      580000.0
9048     1935000.0
2744     3400000.0
2877      430000.0
5896     1440000.0
5817      570000.0
5179      767000.0
12212    2450000.0
6352      925000.0
Name: Price, dtype: float64

In [276]:
for i in range(123,140):
    print("Predictions: %d  \t\t Values:  %d" %(val_predictions[i:i+1], val_y[i:i+1]))

Predictions: 930000  		 Values:  930000
Predictions: 505000  		 Values:  505000
Predictions: 1725000  		 Values:  1725000
Predictions: 800000  		 Values:  800000
Predictions: 1197000  		 Values:  1110000
Predictions: 390000  		 Values:  390000
Predictions: 1300000  		 Values:  1300000
Predictions: 800000  		 Values:  755000
Predictions: 580000  		 Values:  580000
Predictions: 1935000  		 Values:  1935000
Predictions: 3400000  		 Values:  3400000
Predictions: 430000  		 Values:  430000
Predictions: 1400000  		 Values:  1440000
Predictions: 570000  		 Values:  570000
Predictions: 767000  		 Values:  767000
Predictions: 2450000  		 Values:  2450000
Predictions: 925000  		 Values:  925000

# Random Forest

In [277]:
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

In [278]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

In [285]:
forest_model = RandomForestRegressor(random_state=1)

In [280]:
forest_model.fit(train_X, train_y)

RandomForestRegressor(random_state=1)

In [281]:
melb_preds = forest_model.predict(val_X)

In [282]:
print(mean_absolute_error(val_y, melb_preds))

191669.7536453626

In [284]:
tree_model = DecisionTreeRegressor(random_state=1)

In [286]:
tree_model.fit(train_X, train_y)

DecisionTreeRegressor(random_state=1)

In [287]:
melb_predstwo = tree_model.predict(val_X)

In [288]:
print(mean_absolute_error(val_y, melb_predstwo))

262494.3027759845

### Forest was better with 60000~ difference